export const WORDS = [
  "REACT","JAVASCRIPT","NEXTJS","PYTHON","DJANGO","COMPONENTE","INTERFACE",
  "ALGORITMO","BANCO","CLOUD","MOBILE","ARQUITETURA","SERVIDOR","CLIENTE",
  "OTIMIZACAO","PERFORMANCE","ACESSIBILIDADE","ESTADO","PROPRIEDADES","HOOKS",
  "FRAMEWORK","BIBLIOTECA","COMPILADOR","TIPAGEM","INTEGRACAO","MICROSERVICO",
  "AUTENTICACAO","AUTORIZACAO","DEPLOY","PIPELINE","GIT","BRANCH","MERGE",
  "COMMIT","CICD","TYPESCRIPT","CACHE","REDIS","ESCALABILIDADE","LATENCIA",
  "DNS","PROXY","ROTEAMENTO","SSE","WEBSOCKET","FETCH","PROMISE","ASYNC",
  "TESTE","COVERAGE","LAYOUT"
];
